### ISSUE TITLE
Image formatting for select_multiple choices does not work when used alongside choice filters

### ISSUE THREAD

**Issue by DavisRayM** [XLSForm/pyxform#466] opened 2020-09-01 08:41 UTC
#### Software and hardware versions 
pyxform v1.1.0

#### Problem description

When an XLSForm contains a `select_multiple` question that has choices with Image formatting plus a choice filter. The image formatting is ignored, the question body only includes the `name` and `label` and ignores the translation. An example would be this [form](https://drive.google.com/file/d/1ah0jJ3QW0oYWVUAbg04itwwqqYypmIqv/view?usp=sharing):

```
<h:body>
    ...
    <itemset nodeset="instance('birdsseen')/root/item[selected( /data/birds_sighted ,cf)]">
      <value ref="name"/>
      <label ref="label"/>
    </itemset>
</h:body>
```

#### Steps to reproduce the problem

Create an XLSForm with a filtered(choice filter) select_multiple question that has choices with the `media::image` column

#### Expected behavior

Choices with image formatting should display the image in the question.

#### Other information 

- [Full XML](https://pastebin.com/FGaDT2dN); for the XML snippet provided above
- Tested out `select_multiple` without choice_filter and that seems to work fine

**Comment by lognaturel** [comment] 2020-09-02 14:04
Duplicate of https://github.com/XLSForm/pyxform/issues/464.

**Closed by lognaturel** 2020-09-02 14:04 UTC
