### ISSUE TITLE
Curly/smart quotes result in an invalid XForm

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#110] opened 2017-05-14 16:55 UTC
If you have an XLSForm with curly/smart quotes, when you convert it to an XForm, the form will contain invalid (as far as XML and ODK Validate) characters.

#### dumb/straight quotes, form is valid
![dumb-quote](https://cloud.githubusercontent.com/assets/32369/26036017/927da538-389b-11e7-8e89-5bd5509b087c.png)

#### curly/smart quotes, form is invalid
![smart-quote](https://cloud.githubusercontent.com/assets/32369/26036018/927e8494-389b-11e7-85c7-63f94db6bd0d.png)

I propose pyxform either throw a warning or convert the smart quotes to dumb quotes.

**Comment by lognaturel** [comment] 2017-05-31 16:47
I would prefer converting smart quotes to dumb quotes since website examples have smart quotes and the intent is unambiguous.

**Comment by dorey** [comment] 2017-05-31 17:56
Duplicate of #85

**Closed by dorey** 2017-05-31 17:56 UTC

**Comment by lognaturel** [comment] 2017-05-31 18:21
Oh, hah!
