### ISSUE TITLE
Conversion fails if label has language and choice_filter is used

### ISSUE THREAD

**Issue by yanokwa** [XLSForm/pyxform#355] opened 2019-08-30 17:28 UTC
This is a regression with v0.15.0 and I suspect the problem is https://github.com/XLSForm/pyxform/pull/287.

Here's the form in question.
[test.xlsx](https://github.com/XLSForm/pyxform/files/3560905/test.xlsx)

**Fails**
If I have a question with the proper label and a choice_filter, it fails.

<img width="397" alt="Screen Shot 2019-08-30 at 10 20 05 AM" src="https://user-images.githubusercontent.com/32369/64039610-e47f3280-cb0f-11e9-90b8-6f01b1e6083b.png">

```
Traceback (most recent call last):
  File "/usr/local/bin/xls2xform", line 10, in <module>
    sys.exit(main_cli())
  File "/usr/local/lib/python2.7/site-packages/pyxform/xls2xform.py", line 175, in main_cli
    enketo=args.enketo_validate,
  File "/usr/local/lib/python2.7/site-packages/pyxform/xls2xform.py", line 48, in xls2xform_convert
    enketo=enketo,
  File "/usr/local/lib/python2.7/site-packages/pyxform/survey.py", line 899, in print_xform_to_file
    raise error
IndexError: list index out of range
```

**Works**

If I have I change to choice-filter `choice-filter` or `label::English (en)`, then it works.

<img width="397" alt="Screen Shot 2019-08-30 at 10 20 27 AM" src="https://user-images.githubusercontent.com/32369/64039632-ed700400-cb0f-11e9-9066-19353e8d4e95.png">

<img width="423" alt="Screen Shot 2019-08-30 at 10 23 06 AM" src="https://user-images.githubusercontent.com/32369/64039726-2f00af00-cb10-11e9-9b43-3f80234d1ccb.png">

**Comment by yanokwa** [comment] 2019-08-30 17:29
@KeynesYouDigIt I think your PR is the cause of this regression. Can you see if you can reproduce and fix?

**Comment by lognaturel** [comment] 2019-09-11 18:02
I think we should revert #287. I have a narrow fix for this crash at https://github.com/XLSForm/pyxform/compare/master...lognaturel:pyxform-355 but the more I dig into the behavior of #287, the more I think it will be confusing to users.

For example, see test `test_missing_translation_no_default_lang_media_has_no_language`. The error message that form produces is:

>Missing field translations found for English (en) field may not appear as expected.
--
Question missing translation: /pyxform_autotestname/nums
Column missing: image     Default language not set, with missing default translations. Please consider setting a `default_language` in your settings tab to insure questions and options appear as expected.
--
Question missing translation: /pyxform_autotestname/nums
Column missing: long

I think this is an extremely confusing message. I think we should start by designing the desired user experience for #157 before building it. The error messages and the cases in which they're displayed should be clear. The tests should verify that the expected messages are displayed, not just the count of error messages.

**Closed** 2019-09-17 20:03 UTC

**Comment by KeynesYouDigIt** [comment] 2019-10-26 20:03
Sorry missed this thread somehow, looking at a patch now

**Comment by KeynesYouDigIt** [comment] 2019-10-26 21:29
I re added my changes but can't reproduce this issue, the test form converts fine. Is there something specific I did differenly in the form I cnverted? Or were you running a command other than

```
╰─$ python pyxform/xls2xform.py ~/Documents/issue355.xlsx ~/Documents/issue355.xml                                                                                                                                          127 ↵
```

Heres the form I ran this on
```

type | name | label::English (en) | choice_filter
-- | -- | -- | --
select_one country | country | Country |  
select_one region | region | Region | pais=${country}

```

**Comment by KeynesYouDigIt** [comment] 2019-10-26 21:34
Python2 just throws a seperate error

```
(pyxform) ╭─vince@fenrir ~/ODK/pyxform  ‹Vince_issue_157*› 
╰─$ python2 pyxform/xls2xform.py ~/Documents/issue355.xlsx ~/Documents/issue355.xml
Traceback (most recent call last):
  File "pyxform/xls2xform.py", line 14, in <module>
    from pyxform import builder, xls2json
ImportError: No module named pyxform
```

**Comment by KeynesYouDigIt** [comment] 2020-03-28 23:26
Having trouble reproducing this error, here is the test I am using
https://opendatakit.slack.com/archives/C51N25NSE/p1585434315000700


I am going to go forward with a 'safer' fix and PR soon
